set -g default-command /usr/bin/zsh
#set -g mouse on

bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"

#set -g status-utf8 on
#set -g utf8 on

set -g status-fg white
set -g status-bg black

#new -n shell 
#neww -n kaniner zsh -c "storkundo && make rabbit-listener"
#splitw -p 50 -t 0 chat && make rabbit-listener 
#neww -n servers chat && make server
#neww -n misc es52
